### ISSUE TITLE
Map filepath can't be pulled from variables / defs in map-from-file branch

### ISSUE THREAD

**Issue by aforry** [seniordesign2/game-client#5]
We can now pull maps from the local file system for the project out of the assets folder.

However when passed to the filereader.clj it MUST be specified in direct quotes or errors are thrown.

Example:
(load-map "assets/maps/map1.txt") ;; this works

(def map-path "assets/maps/map1.txt1")
(load-map map-path) ;; this throws an error

We need a method of passing the argument as a variable because later on we will want to change the filepath to navigate multiple maps.

**Comment by numberQ** [comment]
After looking into macros, it seems like this is happening because a Clojure macro builds a list to evaluate out of the literal symbol passed to it, not the data it represents. There are ways to "unquote" the symbol, but I had trouble doing that without also "unquoting" `slurp` and `io/file`, which ClojureScript can't evaluate.

http://www.braveclojure.com/writing-macros/

**Comment by aforry** [comment]
Until we have a better fix, I suggest for now we use different methods for maps that simply pass the string literals we need upon being called.  Another "selector" method could call the map method we need.  This could all be replaced by a permanent singular method if we determine a work around for the slurp and io/file "unquoting" issue.

**Comment by numberQ** [comment]
This has been resolved by loading every map at compile time, so we can choose which one we want at run time.
